rootProject.name = "LiquorManiac"
include("batch-scheduler")
include("bff")
include("chat")
include("gpt")
include("liquor")
include("user")
include("common")
include("common:client", "common:client:client-util-dep")
include("common:core", "common:core:core-web")
include("common:domain", "common:domain:domain-user")
include("common:others", "common:others:redis-config")